import "../src/load-env.js";
import { randomUUID } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { calculateHealthScore } from "@homefax/contracts";
import { hashPassword } from "@homefax/auth";
import { buildChain, sha256, type ChainableEvent } from "@homefax/ledger";
import {
  fixtureAccounts,
  fixtureContractors,
  fixtureProperties,
  SHOWCASE_TOKEN_ID,
} from "@homefax/fixtures";

/**
 * Emits the seed as plain SQL.
 *
 * Needed because a hosted database may only be reachable through a management
 * API rather than a connection string. The hashes here are produced by the
 * same code the seeder uses — real scrypt for passwords, real SHA-256 for the
 * ledger and for document bytes — so the exported rows are byte-identical to
 * what `pnpm db:seed` would write locally.
 */

const q = (value: string | null): string =>
  value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`;
const j = (value: unknown): string => q(JSON.stringify(value));
const n = (value: number | null): string => (value === null ? "NULL" : String(value));
const b = (value: boolean): string => (value ? "true" : "false");
const bytea = (buffer: Buffer): string => `'\\x${buffer.toString("hex")}'::bytea`;

async function main(): Promise<void> {
  const lines: string[] = [
    "-- Generated by packages/db/scripts/export-seed-sql.ts. Do not edit by hand.",
    "BEGIN;",
    // Idempotent: a re-run replaces the dataset rather than doubling it.
    'TRUNCATE TABLE "ai_extraction_jobs","token_transfers","jobs","saved_properties",',
    '  "home_claims","claims","ownership_periods","property_systems","property_documents",',
    '  "property_events","properties","contractors","profiles","document_blobs" RESTART IDENTITY CASCADE;',
  ];

  const profileIds = new Map<string, string>();
  for (const account of fixtureAccounts) {
    const id = randomUUID();
    profileIds.set(account.email, id);
    lines.push(
      `INSERT INTO "profiles" ("id","email","password_hash","display_name","initials","role","role_label","avatar_bg","badge","phone","brokerage","plan","owned_token_id","contractor_id") VALUES (` +
        [
          q(id),
          q(account.email),
          q(await hashPassword(account.password)),
          q(account.name),
          q(account.initials),
          q(account.role),
          q(account.roleLabel),
          q(account.avatarBg),
          q(account.badge),
          q(account.phone),
          q(account.brokerage),
          q(account.role === "contractor" ? "verified_source" : "free"),
          q(account.ownedTokenId),
          q(account.contractorId),
        ].join(",") +
        ");",
    );
  }

  for (const contractor of fixtureContractors) {
    lines.push(
      `INSERT INTO "contractors" ("public_id","name","initials","trade","license_number","verified","verified_since","service_area","service_zips","job_count","phone","blurb") VALUES (` +
        [
          q(contractor.id),
          q(contractor.name),
          q(contractor.initials),
          q(contractor.trade),
          q(contractor.license),
          b(contractor.verified),
          q(contractor.since),
          q(contractor.area),
          q(contractor.zips),
          n(contractor.jobCount),
          q(contractor.phone),
          q(contractor.blurb),
        ].join(",") +
        ");",
    );
  }

  const propertyIds = new Map<string, string>();
  for (const fixture of fixtureProperties) {
    const propertyId = randomUUID();
    propertyIds.set(fixture.tokenId, propertyId);

    const health = calculateHealthScore(
      fixture.systems.map((s) => ({ key: s.key, status: s.status })),
    );

    lines.push(
      `INSERT INTO "properties" ("id","token_id","address_line1","city","state","postal_code","parcel_id","property_type","year_built","bedrooms","bathrooms","living_sqft","lot_sqft","current_estimated_value","current_health_score","is_showcase") VALUES (` +
        [
          q(propertyId),
          q(fixture.tokenId),
          q(fixture.address),
          q(fixture.city),
          q(fixture.state),
          q(fixture.postalCode),
          q(fixture.parcelId),
          q(fixture.propertyType),
          n(fixture.yearBuilt),
          n(fixture.bedrooms),
          n(fixture.bathrooms),
          n(fixture.livingSqft),
          n(fixture.lotSqft),
          n(fixture.estimatedValue),
          n(health.score),
          b(fixture.isShowcase),
        ].join(",") +
        ");",
    );

    const chainable: ChainableEvent[] = fixture.events.map((e) => ({
      id: e.id,
      eventType: e.eventType,
      occurredAt: e.occurredAt,
      title: e.title,
      description: e.description || null,
      verificationLevel: e.verificationLevel,
      visibility: e.visibility,
      metadata: { summary: e.meta },
    }));
    const links = new Map(buildChain(chainable).map((l) => [l.eventId, l]));

    const eventIds = new Map<string, string>();
    let documentIndex = 0;

    for (const event of fixture.events) {
      const link = links.get(event.id)!;
      const eventId = randomUUID();
      eventIds.set(event.id, eventId);

      lines.push(
        `INSERT INTO "property_events" ("id","public_id","property_id","event_type","occurred_at","title","description","verification_level","visibility","metadata","previous_hash","event_hash") VALUES (` +
          [
            q(eventId),
            q(event.id),
            q(propertyId),
            q(event.eventType),
            q(event.occurredAt),
            q(event.title),
            q(event.description || null),
            q(event.verificationLevel),
            q(event.visibility),
            `${j({ summary: event.meta })}::jsonb`,
            q(link.previousHash),
            q(link.hash),
          ].join(",") +
          ");",
      );

      for (const document of event.documents) {
        documentIndex += 1;
        const safeName = document.name.replace(/[^A-Za-z0-9._-]/g, "_");
        const storageKey = `${fixture.tokenId}/seed-${String(documentIndex).padStart(3, "0")}-${safeName}.txt`;
        const bytes = Buffer.from(document.text, "utf8");
        const digest = sha256(bytes);

        lines.push(
          `INSERT INTO "document_blobs" ("storage_key","content_type","bytes","sha256") VALUES (${q(storageKey)},'text/plain',${bytea(bytes)},${q(digest)});`,
        );
        lines.push(
          `INSERT INTO "property_documents" ("property_id","event_id","file_name","storage_path","mime_type","file_size","document_type","visibility","sha256") VALUES (` +
            [
              q(propertyId),
              q(eventId),
              q(document.name),
              q(storageKey),
              "'text/plain'",
              n(bytes.byteLength),
              q(document.kind),
              q(document.visibility),
              q(digest),
            ].join(",") +
            ");",
        );
      }
    }

    for (const system of fixture.systems) {
      const source = system.sourceEventId ? eventIds.get(system.sourceEventId) : null;
      lines.push(
        `INSERT INTO "property_systems" ("property_id","system_type","display_name","status","verification_level","source_event_id","rows","hidden") VALUES (` +
          [
            q(propertyId),
            q(system.key),
            q(system.name),
            q(system.status),
            q(system.verificationLevel),
            source ? q(source) : "NULL",
            `${j(system.rows)}::jsonb`,
            b(system.hidden),
          ].join(",") +
          ");",
      );
    }

    for (const period of fixture.ownership) {
      lines.push(
        `INSERT INTO "ownership_periods" ("property_id","sequence_number","label","range_label","is_current","verification_level") VALUES (` +
          [
            q(propertyId),
            n(period.sequenceNumber),
            q(period.label),
            q(period.rangeLabel),
            b(period.isCurrent),
            q(period.verificationLevel),
          ].join(",") +
          ");",
      );
    }
  }

  const agentId = profileIds.get("agent@homefax.demo")!;
  const ownerId = profileIds.get("owner@homefax.demo")!;
  const showcaseId = propertyIds.get(SHOWCASE_TOKEN_ID)!;

  lines.push(
    `INSERT INTO "claims" ("property_id","agent_id","agent_name","status","method","mls_number","claimed_at","expires_at") VALUES (${q(showcaseId)},${q(agentId)},'Alex Morgan','active','MLS','9182446','2026-08-14','2026-11-12');`,
    `INSERT INTO "home_claims" ("property_id","owner_id","status","method","verified_at") VALUES (${q(showcaseId)},${q(ownerId)},'active','County record match','2026-02-11');`,
    `INSERT INTO "saved_properties" ("profile_id","property_id") VALUES (${q(agentId)},${q(propertyIds.get("HF-US-CO-DEN-00004501")!)});`,
    "COMMIT;",
  );

  const sql = lines.join("\n");
  const target = process.argv[2] ?? "seed.sql";
  await writeFile(target, sql, "utf8");
  console.log(`Wrote ${target} (${sql.length} bytes, ${lines.length} statements).`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
